name: UC update check

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    
jobs:
  extract_version:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Git
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install requests library
        run: python -m pip install requests

      - name: Run Python Script
        run: |
          python - <<EOF
          import requests
          import re
          import os
          import sys


          # Download webpage content
          response = requests.get('https://releases.usercentrics.com/loadMoreNews?app_id=nGxJmmsl20682&role=cmpv1%3Bcmpv2%3B&language=EN&user_id=70bb2f11-095e-415d-9712-2cf59a885f98&lastname=Cat&firstname=Blue&category=browser%20ui&publicPage=true&post=false&basePath=%2F%2Freleases.usercentrics.com%2Fen&standaloneLogoUrl=https%3A%2F%2Fstatic.getbeamer.com%2FnGxJmmsl20682%2Flogo_3269.png')
          html_content = response.text

          # Parse version from HTML body using regex
          version_pattern = r'Version (\d+\.\d+\.\d+)'
          version_match = re.search(version_pattern, html_content)
          if version_match:
              version = version_match.group(1)
              version = version.replace("Version ", "")  # Remove the "Version " prefix
              print("Version:", version)

              previous_version = ""
              if os.path.exists("src/bundles/usercentrics.version"):
                  with open("src/bundles/usercentrics.version", "r") as f:
                      previous_version = f.read().strip()

              if version != previous_version:
                  print("Version has changed.", version, previous_version)

                  with open("usercentrics.version", "w") as f:
                      f.write(version)

                  # Download JS file
                  js_url = f"https://app.usercentrics.eu/browser-ui/{version}/bundle.js"
                  response = requests.get(js_url)
                  with open("usercentrics.js", "wb") as f:
                      f.write(response.content)
                  print("JS file downloaded.")

              else:
                  print("Version is the same as previous.")
                  sys.exit(1)

          else:
              print("Version not found.")
              sys.exit(1)
          EOF

      - name: Upload Version Artifact
        uses: actions/upload-artifact@v2
        with:
          name: version-artifact
          path: usercentrics.version

      - name: Upload JS Bundle
        uses: actions/upload-artifact@v2
        with:
          name: uc-bundle-artifact
          path: usercentrics.js

  create-pr:
    needs: extract_version

    runs-on: ubuntu-latest
    steps:

      # - name: Download Zip
      #   run: |
      #     cat artifact/usercentrics.version
      #     version=$(cat artifact/usercentrics.version)
      #     echo "Using version: $version"

      - name: Set up Git
        uses: actions/checkout@v3

      - name: Download JS Artifact
        uses: actions/download-artifact@v2
        with:
          name: uc-bundle-artifact

      - name: Download Version Artifact
        uses: actions/download-artifact@v2
        with:
          name: version-artifact

      - name: Move files to correct location
        run: |
          # cd spa
          # mkdir -p src/bundles
          mv ./usercentrics.js src/bundles/usercentrics.js
          mv ./usercentrics.version src/bundles/usercentrics.version

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add new Usercentrics version
          title: Add new Usercentrics version
          branch: uc-update
          base: main
