name: Inline Python Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Parse UI version
        run: |
          python - <<EOF
          import requests
          import re

          # Download webpage content
          response = requests.get('https://releases.usercentrics.com/en?category=browser+ui&role=cmpv1%3Bcmpv2%3B')
          html_content = response.text

          # Parse version from HTML body using regex
          version_pattern = r'<h4.*?>(.*?)<\/h4>'
          version_match = re.search(version_pattern, html_content)
          if version_match:
              version = version_match.group(1)
              print("Version:", version)
          else:
              print("Version not found.")

          EOF
