name: Extract Version

on:
  push:
    branches:
      - main

jobs:
  extract_version:
    runs-on: ubuntu-latest
    steps:

      # - name: Load Previous Version Artifact
      #   id: load_previous_version
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: version-artifact
      #     path: previous_version
      #   if-no-files-found: ignore

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install requests library
        run: python -m pip install requests

      - name: Run Python Script
        run: |
          python - <<EOF
          import requests
          import re
          import os

          # Download webpage content
          response = requests.get('https://releases.usercentrics.com/loadMoreNews?app_id=nGxJmmsl20682&role=cmpv1%3Bcmpv2%3B&language=EN&user_id=70bb2f11-095e-415d-9712-2cf59a885f98&lastname=Cat&firstname=Blue&category=browser%20ui&publicPage=true&post=false&basePath=%2F%2Freleases.usercentrics.com%2Fen&standaloneLogoUrl=https%3A%2F%2Fstatic.getbeamer.com%2FnGxJmmsl20682%2Flogo_3269.png')
          html_content = response.text

          # Parse version from HTML body using regex
          version_pattern = r'Version (\d+\.\d+\.\d+)'
          version_match = re.search(version_pattern, html_content)
          if version_match:
              version = version_match.group(1)
              version = version.replace("Version ", "")  # Remove the "Version " prefix
              print("Version:", version)

              previous_version = ""
              # if os.path.exists("previous_version/version.txt"):
              #     with open("previous_version/version.txt", "r") as f:
              #         previous_version = f.read().strip()

              if version != previous_version:
                  print("Version has changed.", version, previous_version)

                  with open("version.txt", "w") as f:
                      f.write(version)

                  # Download JS file
                  js_url = f"https://app.usercentrics.eu/browser-ui/{version}/bundle.js"
                  response = requests.get(js_url)
                  with open("usercentrics.js", "wb") as f:
                      f.write(response.content)
                  print("JS file downloaded.")

              else:
                  print("Version is the same as previous.")

          else:
              print("Version not found.")
          EOF

      - name: Upload Version Artifact
        uses: actions/upload-artifact@v2
        with:
          name: version-artifact
          path: version.txt

      - name: Upload JS Bundle
        uses: actions/upload-artifact@v2
        with:
          name: uc-bundle-artifact
          path: usercentrics.js

  create-pr:
    needs: extract_version

    runs-on: ubuntu-latest
    steps:

      # - name: Download Zip
      #   run: |
      #     cat artifact/version.txt
      #     version=$(cat artifact/version.txt)
      #     echo "Using version: $version"

      - name: Check out abaxsoraszem/spa repository
        uses: actions/checkout@v2
        with:
          repository: abaxsoraszem/spa


      - name: Download Version Artifact
        uses: actions/download-artifact@v2
        with:
          name: version-artifact
          path: artifact

      - name: Create New Branch
        run: |
          pwd
          ls -al
          # timestamp=$(date +%s)
          # cd spa
          git checkout -b uc-update-timestamp
          git config user.name "abaxsoraszem"
          git config user.email "abax.soraszem@gmail.com"

      - name: Add usercentrics.js to Repo
        run: |
          # cd spa
          # mkdir -p src/bundles
          cp ./artifact/usercentrics.js src/bundles/usercentrics.js

      - name: Commit and Push Changes
        run: |
          # cd spa
          git add src/bundles/usercentrics.js
          git commit -m "Add usercentrics.js new version"
          git push origin uc-update-timestamp

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add usercentrics.js
          title: Update usercentrics.js
          branch: uc-update-timestamp
          base: main
